### ISSUE TITLE
How do I get artist ID?

### ISSUE THREAD

**Issue by mabushey** [michiwend/gomusicbrainz#6]
On the musicbrainz web site, searching for the artist `Slave Raider` ( https://musicbrainz.org/search?query=slave+raider&type=artist&method=indexed ), I see the Artist ID is 49950dec-e4c4-4177-808d-bab8ab028665.

In search_artist.go, I changed the artist.

Name: Slave Raider             Score: 100

All the 100 does is tell me how good of a match `49950dec-e4c4-4177-808d-bab8ab028665` ID is, but it doesn't provide the ID! I fail to even grasp what this purpose of this example is. How do I get the artistID?

**Comment by michiwend** [comment]
just change artist.Name to artist.ID in the example and you'll see the artist’s mbid instead. The purpose of this example is to show you how you can use gomusicbrainz to do a simple search request.

**Comment by mabushey** [comment]
That was simple! Thank you! :)
